name: ExtrapolaTED
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - pytorch-cuda=11.8
  - pyarrow
  - pytorch
  - torchvision
  - torchaudio
  - requests
  - pandas
  - pillow
  - numpy
  - pip
  - pip:
    - uform
    - usearch
    - simsimd
    - stringzilla
    - datasets
    - transformers
    - mwparserfromhell
    - apache_beam
    - ipykernel
    - jupyter
    - ipywidgets
