name: ExtrapolaTED
channels:
  - pytorch
  - nvidia
dependencies:
  - pytorch-cuda=11.8
  - pytorch
  - torchvision
  - torchaudio
  - pip:
    - python=3.10
    - uform
    - usearch
    - simsimd
    - stringzilla
    - datasets
    - transformers
    - mwparserfromhell
    - apache_beam
    - ipykernel
    - jupyter
    - ipywidgets
    - pandas
    - pillow
    - pyarrow
    - requests
    - numpy
